### ISSUE TITLE
Problems with SublimeLinter

### ISSUE THREAD

**Issue by camloken** [gornostal/Modific#102]
I noticed that Modifics gutter icon hides linter error icons. I changed the Modific gutter icon to dot and it works (with SublimeLinters default gutter theme). However, Modifics default arrow icon hides linter warnings. Not good.

**Comment by gornostal** [comment]
Hi,

Could you send a screen shot of liner icons/warnings that get hidden?

**Comment by camloken** [comment]
I noticed changing Modifics icon to the dot does not work anymore. I thought SublimeLinter overwrote Modifics icon and showed errors, but it doesn't seem to do that anymore. It doesn't matter if I change Modifics gutter icon or not.

![screenshot](https://cloud.githubusercontent.com/assets/2279954/25357623/b80431dc-28fb-11e7-80ae-e1952951d85a.png)

**Comment by gornostal** [comment]
It's a known issue of ST that one plugin replaces gutter icons of another one.
If this is the case for you, there is nothing we can do here. Sorry :(

I use linters too, but I configured them to outline part of the code that has error rather than draw icon in the gutter. 
I guess this is not what you are looking for, but just a suggestion.
